name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  id-token: write # to enable use of OIDC for trusted publishing and npm provenance

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.head_ref || github.ref_name }}
        uses: actions/checkout@v6.0.3

      - name: Setting up pnpm
        uses: pnpm/action-setup@v6.0.8

      - name: Install packages
        run: pnpm ci

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test:coverage

      - name: Build
        run: pnpm build

  publish:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.head_ref || github.ref_name }}
        uses: actions/checkout@v6.0.3

      - name: Setting up pnpm
        uses: pnpm/action-setup@v6.0.8

      - name: Install packages
        run: pnpm ci

      - name: Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
