name: Continuous Integration

on:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v6

      - name: Setting up pnpm
        uses: pnpm/action-setup@v5

      - name: Setting up nodejs
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install packages
        run: pnpm i

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test:coverage

      - name: Build
        run: pnpm build

  publish:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v6

      - name: Setting up pnpm
        uses: pnpm/action-setup@v5

      - name: Setting up nodejs
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install packages
        run: pnpm i

      # semantic-release only officially supports npm (https://github.com/semantic-release/npm/issues/280)
      # I tried creating an alias, but commands are executed in sub shells (https://github.com/VentionCo/mm-machine-logic/pull/5186)
      # I tried @anolilab/semantic-release-pnpm but it doesn't work with the github registry (https://github.com/VentionCo/mm-machine-logic/pull/5187)
      # So now I'll delete the devEngines restriction just before publishing.
      - name: Allow npm for @semantic-release/npm
        run: jq 'del(.devEngines)' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Release
        run: pnpm semantic-release
